# Base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /opt/traccar

# Copy the Traccar server JAR file to the container
COPY traccar-server.jar .

# Expose the default Traccar port
EXPOSE 8082

# Run the Traccar server
CMD ["java", "-jar", "traccar-server.jar"]

