# Base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the Traccar server JAR file to the container
COPY target/traccar-server.jar .

# Expose the default Traccar port
EXPOSE 8082

# Run the Traccar server
CMD ["java", "-jar", "traccar-server.jar"]

