name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tekka.azurecr.io/traccar:latest
          build-args: |
            TRACCAR_DATABASE=mysql
            TRACCAR_WEB_PORT=8082

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tekka.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
