name: Java CI with Gradle

on:
  push:
    branches: [DockTest]
  pull_request:
    branches: [DockTest]

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - run: ./gradlew build --no-daemon --warning-mode=fail

  docker-build:
    name: Build Docker image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tekka.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.ubuntu
          tags: tekka.azurecr.io/traccar:v5
          platforms: linux
          push: true
        

  deploy:
    name: Deploy to Azure VM
    needs: docker-build
    runs-on: ubuntu-latest

    env:
      AZURE_VM_IP: 13.69.28.186
      VM_USERNAME: saidAzure
      VM_PASSWORD: ${{ secrets.VM_PASSWORD_WS }}

    steps:
      - name: Install sshpass
        run: |
          choco install -y sshpass
      - name: Deploy Docker image to Azure VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD_WS }}" ssh -o StrictHostKeyChecking=no ${{ env.VM_USERNAME }}@${{ env.AZURE_VM_IP }} '
            docker login tekka.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
            docker stop tekka || true
            docker rm tekka || true
            docker pull tekka.azurecr.io/traccar:v5
            docker run -d --name tekka -p 8082:8082 tekka.azurecr.io/traccar:v5'
